### ISSUE TITLE
Temporarily polish website for launch

### ISSUE THREAD

**Issue by filippociandy10** [UofA-Blueprint/issues#107]
Acceptance Criteria:
- [x] C̶o̶n̶s̶o̶l̶i̶d̶a̶t̶e̶ ̶c̶o̶m̶p̶o̶n̶e̶n̶t̶ ̶i̶n̶ ̶e̶a̶c̶h̶ ̶p̶a̶g̶e̶ ̶a̶n̶d̶ ̶e̶n̶s̶u̶r̶e̶ ̶t̶h̶e̶y̶ ̶a̶r̶e̶ ̶w̶o̶r̶k̶i̶n̶g̶ ̶p̶r̶o̶p̶e̶r̶l̶y̶
- [x] E̶n̶s̶u̶r̶e̶ ̶d̶e̶s̶i̶g̶n̶ ̶o̶f̶ ̶t̶h̶e̶ ̶w̶e̶b̶s̶i̶t̶e̶ ̶f̶o̶l̶l̶o̶w̶s̶ ̶f̶i̶g̶m̶a̶
- [x] Add "Under construction" banner on top of all page
- [x] Change the app metadata to improve SEO (e.g., website description on google)
- [x] Make sure the website doesn't break
- [ ] Push develop to main at the end of the sprint
- [x] Add mock data when necessary
- [x] send survey to ask for members' info

**Comment by dimassudjito** [comment]
@filippociandy10 We want to release the website at the end of sprint 5 (announce in LinkedIn, Instagram, etc), but it won't still be completed so a couple things need to be done:
- add "Under construction" banner on top of all page
- change the app metadata to improve SEO (e.g., website description on google)
- make sure the website doesn't break
- make sure none of the tests break
- push develop to main at the end of the sprint

We should track it from an epic. Maybe we can add it to #1
