### ISSUE TITLE
Research on how to upload and store photo on verification to the backend

### ISSUE THREAD

**Issue by filippociandy10** [UofA-Blueprint/issues#134]
As a developer, I want to be able to store photo in a secure and efficient way from the frontend to the backend. Find different ways on how to store the screenshot photo in the backend and document it. 

We want to store screenshots that user will submit to verify their status as international students.

Acceptance Criteria:

- [x] Explore different ways how to store the screenshot in the backend.
- [x]  Report finding in document (e.g. in [shared drive](https://drive.google.com/drive/u/0/folders/1cBagZBN93T-0uuWOYCmGVc3KrofC0xre))

**Comment by ArmaanKatyal** [comment]
https://user-images.githubusercontent.com/66411529/186740759-3d41ab5a-9122-4fef-a5cb-54c044d0d06b.mp4

In this video, you can see how the API route is implemented. If you have any comments or changes, do let me know
@filippociandy10 @dimassudjito
